/* Generated By:JavaCC: Do not edit this line. AnalizadorLexicoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorLexicoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TERMINAL = 6;
  /** RegularExpression Id. */
  int PALABRARESERVADALEER = 7;
  /** RegularExpression Id. */
  int PALABRARESERVADASI = 8;
  /** RegularExpression Id. */
  int PALABRARESERVADAENTONCES = 9;
  /** RegularExpression Id. */
  int PALABRARESERVADASINO = 10;
  /** RegularExpression Id. */
  int PALABRARESERVADAFINSI = 11;
  /** RegularExpression Id. */
  int PALABRARESERVADAESCRIBIR = 12;
  /** RegularExpression Id. */
  int TIPODATOENTERO = 13;
  /** RegularExpression Id. */
  int TIPODATOCADENA = 14;
  /** RegularExpression Id. */
  int OPERADORCOMPARACIONMAYOR = 15;
  /** RegularExpression Id. */
  int OPERADORCOMPARACIONMENOR = 16;
  /** RegularExpression Id. */
  int CONCATENACION = 17;
  /** RegularExpression Id. */
  int COMENTARIO = 18;
  /** RegularExpression Id. */
  int ABRIRCORCHETE = 19;
  /** RegularExpression Id. */
  int CERRARCORCHETE = 20;
  /** RegularExpression Id. */
  int CADENAS = 21;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 22;
  /** RegularExpression Id. */
  int ASIGNACION = 23;
  /** RegularExpression Id. */
  int OPERADORSUMA = 24;
  /** RegularExpression Id. */
  int OPERADORMULTIPLICACION = 25;
  /** RegularExpression Id. */
  int OPERADORDIVIDIDO = 26;
  /** RegularExpression Id. */
  int OPERADORMENOS = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\".\"",
    "\"Leer\"",
    "\"Si\"",
    "\"Entonces\"",
    "\"Sino\"",
    "\"Finsi\"",
    "\"Escribir\"",
    "\"Numero\"",
    "\"Cadena\"",
    "\">\"",
    "\"<\"",
    "\"@\"",
    "<COMENTARIO>",
    "\"[\"",
    "\"]\"",
    "<CADENAS>",
    "<IDENTIFICADOR>",
    "\"=\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"-\"",
  };

}
